### ISSUE TITLE
Unnecessary plus operators on ChatColor

### ISSUE THREAD

**Issue by Sxtanna** [Deanveloper/KBukkit#1]
# Kotlin has String Interpolation

### Interpolation example
```kotlin 
val hello = "${ChatColor.BOLD}${ChatColor.RED}Hello"
``` 
*Would compile*

**vs** 

### Concatenation example
```kotlin
val hello = ChatColor.BOLD + ChatColor.RED + "Hello"
``` 
*Would not compile*

  
https://kotlinlang.org/docs/reference/basic-types.html#string-templates

**Comment by deanveloper** [comment]
Either way works. KBukkit specifies extension operator functions on both Bukkit's ChatColor and Bungee's ChatColor to be able to use the "+" symbol with either of them. While using string templates is possible (and honestly probably much cleaner), the use of the "+" operator is something that many people would use to prefix a string.

**Comment by Remering** [comment]
Unfortunately, "message" + ChatColor.RED doesn't work.You may declare "operator fun String.plus(color:ChatColor)" ,but it seems needless.
