### ISSUE TITLE
How about using inline function?

### ISSUE THREAD

**Issue by Remering** [Deanveloper/KBukkit#3]
There are many short methods with lambdas and they may be declared as "inline" to promote performance.
（Sorry for my poor English.XD）

**Comment by deanveloper** [comment]
If you're talking about `KBukkitRunnable.kt` then it can't be inline, at best it will be `crossinline`, although I'll see where I can go with that when I get an IDE set up

**Comment by Remering** [comment]
Merry Christmas:)
So do they.
I was wondering whether"BukkitRunable.（）" can be replaced with SAM such as "（）->Unit" ,just like using "Thread({})" to new an instance,then they can be inlined.But it doesn't work.
Sorry for my stupidness.Close it please.
