### ISSUE TITLE
Inventory create wrong argument type

### ISSUE THREAD

**Issue by MrFreezeex** [Deanveloper/KBukkit#4]
Hey,

owner should be of type InventoryHolder? and not only InventoryHolder in Inventories.create method.

https://github.com/Deanveloper/KBukkit/blob/e4f249b054349f31e4b4a8dae344d20235484a59/src/main/kotlin/com/deanveloper/kbukkit/util/KBukkitUtil.kt#L504

regards

**Comment by deanveloper** [comment]
Yup! My bad, I'll fix that.

**Comment by deanveloper** [comment]
https://github.com/Deanveloper/KBukkit/commit/9c0025630e409392433f9cdb7b9fa9f8cbf70948#diff-e750e1abea4c7f9cbda163f743859a76R504

**Comment by deanveloper** [comment]
Fixed in 1.3
